### ISSUE TITLE
"add" is not saving ID in the loaded object

### ISSUE THREAD

**Issue by mcoquet** [rsoares/nomnom#10]
this causes actions that try to talk to hoodie to fail because the objects are expected to have an ID once they are saved, but they don't when you first create them :fearful: 

Proposed solution: On the hoodie "done" handler, update the "visible" object to have the right id.

**Comment by rsoares** [comment]
I did fix this directly on master. It's pushed. Don't ask me why I did it... Too complicated :dancers:
